--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 19/3/2016 01:21:02
-- Server version: 5.5.45
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE svendas;

--
-- Definition for table caixa
--
DROP TABLE IF EXISTS caixa;
CREATE TABLE caixa (
  caixa_id INT(11) NOT NULL AUTO_INCREMENT,
  caixa_data_abre DATE DEFAULT NULL,
  caixa_valor DOUBLE(9, 2) DEFAULT 0.00,
  caixa_data_fecha DATE DEFAULT NULL,
  caixa_inicial DOUBLE(9, 2) DEFAULT 0.00,
  caixa_usuario INT(11) DEFAULT NULL,
  PRIMARY KEY (caixa_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table clientes
--
DROP TABLE IF EXISTS clientes;
CREATE TABLE clientes (
  cli_id INT(11) NOT NULL AUTO_INCREMENT,
  cli_nome VARCHAR(50) DEFAULT NULL,
  cli_endereco VARCHAR(100) DEFAULT NULL,
  cli_numero VARCHAR(20) DEFAULT NULL,
  cli_bairro VARCHAR(50) DEFAULT NULL,
  cli_cidade VARCHAR(50) DEFAULT NULL,
  cli_fone VARCHAR(20) DEFAULT NULL,
  cli_celular VARCHAR(20) DEFAULT NULL,
  cli_rg VARCHAR(20) DEFAULT NULL,
  cli_cpf VARCHAR(20) DEFAULT NULL,
  cli_profissao VARCHAR(50) DEFAULT NULL,
  cli_data_nasc DATE DEFAULT NULL,
  PRIMARY KEY (cli_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table produtos
--
DROP TABLE IF EXISTS produtos;
CREATE TABLE produtos (
  pro_id INT(11) NOT NULL AUTO_INCREMENT,
  pro_nome VARCHAR(100) DEFAULT NULL,
  pro_barras VARCHAR(20) DEFAULT NULL,
  pro_ref VARCHAR(20) DEFAULT NULL,
  pro_custo DOUBLE(9, 2) NOT NULL DEFAULT 0.00,
  pro_preco DOUBLE(9, 2) DEFAULT 0.00,
  pro_preco_prazo DOUBLE(9, 2) DEFAULT 0.00,
  pro_estoque INT(11) DEFAULT NULL,
  PRIMARY KEY (pro_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table usuarios
--
DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  user_nome VARCHAR(50) DEFAULT NULL,
  user_nome_completo VARCHAR(80) DEFAULT NULL,
  user_senha VARCHAR(40) DEFAULT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table itens
--
DROP TABLE IF EXISTS itens;
CREATE TABLE itens (
  iten_id INT(11) NOT NULL AUTO_INCREMENT,
  iten_produto INT(11) DEFAULT NULL,
  iten_qtd INT(11) DEFAULT NULL,
  iten_pedido VARCHAR(20) DEFAULT NULL,
  iten_preco DOUBLE(9, 2) DEFAULT 0.00,
  iten_preco_prazo DOUBLE(9, 2) DEFAULT NULL,
  PRIMARY KEY (iten_id),
  CONSTRAINT FK_itens_produtos_pro_id FOREIGN KEY (iten_produto)
    REFERENCES produtos(pro_id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table pedidos
--
DROP TABLE IF EXISTS pedidos;
CREATE TABLE pedidos (
  ped_id INT(11) NOT NULL AUTO_INCREMENT,
  ped_data DATE DEFAULT NULL,
  ped_codigo VARCHAR(20) DEFAULT NULL,
  ped_cliente INT(11) DEFAULT NULL,
  ped_usuario INT(11) DEFAULT NULL,
  ped_forma_pag INT(11) DEFAULT NULL,
  ped_fechado ENUM('SIM','NAO') DEFAULT NULL,
  ped_faturado ENUM('SIM','NAO') DEFAULT NULL,
  PRIMARY KEY (ped_id),
  CONSTRAINT FK_pedidos_clientes_cli_id FOREIGN KEY (ped_cliente)
    REFERENCES clientes(cli_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_pedidos_usuarios_user_id FOREIGN KEY (ped_usuario)
    REFERENCES usuarios(user_id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table caixa
--

-- Table svendas.caixa does not contain any data (it is empty)

-- 
-- Dumping data for table clientes
--

-- Table svendas.clientes does not contain any data (it is empty)

-- 
-- Dumping data for table produtos
--

-- Table svendas.produtos does not contain any data (it is empty)

-- 
-- Dumping data for table usuarios
--

-- Table svendas.usuarios does not contain any data (it is empty)

-- 
-- Dumping data for table itens
--

-- Table svendas.itens does not contain any data (it is empty)

-- 
-- Dumping data for table pedidos
--

-- Table svendas.pedidos does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;